version: 0.0
os: linux
files:
  - source: content/
    destination: /var/@project.artifactId@
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/application_start
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 60
      runas: root
